AllCops:
  Include:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
  Exclude:
    - 'gem/**/*'

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Exclude:
    - 'lib/masterminds/*.rb'
    - 'lib/schemes/*.rb'
    - 'lib/villain_groups/*.rb'
