version: "3"
services:
  dev:
    build: .
    ports:
    - "8080:8080"
    volumes:
    - .:/app/:rw
    command: >-
      sh -c '
        if test -d node_modules; then
          echo node_modules_exists ;
        else
          cp -a /tmp/node_modules /app;
        fi &&
        yarn install &&
        yarn run dev-server
      '
