version: 2
jobs:
  build:
    working_directory: ~/legendary-countdown
    docker:
      - image: docker:17.06.0-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: bundle
          command: |
            pwd
            ls -la
            ./bundle.sh
            ls -la dist
      - store_artifacts:
          path: ./dist/
