version: 2
jobs:
  build:
    working_directory: ~/legendary-countdown
    docker:
      - image: docker:17.06.0-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: bundle
          command: docker-compose up --build bundle
      - store_artifacts:
          path: ./dist/
