version: 2
jobs:
  build:
    working_directory: ~/legendary-countdown
    docker:
      - image: docker:17.06.0
    steps:
      - setup_remote_docker
      - run: |
          ./bundle.sh
          ls -la dist
